server {
    listen 80;

    # Весь трафик приходит с префиксом /oranges/ от главного nginx
    location /oranges/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }
}
